#!/bin/bash

# Enable rspamd for all accounts

# If they have no filters configured, give them a baseline
for i in $(find /etc/virtual -name filter.conf)
        do
                if ! grep -q "high_score_block" $i; then
                        echo "high_score=25" >> $i
                        echo "high_score_block=yes" >> $i
                        echo "where=delete" >> $i
                fi
        done

# Rspamd configs won't be generated by DirectAdmin unless user_prefs exists, so handle it
for username in $(ls /usr/local/directadmin/data/users);
        do
                DIR=/home/$username/.spamassassin
                mkdir -p $DIR
                UP=$DIR/user_prefs
                  if [ ! -s ${UP} ]; then
                     echo 'required_score 25.0' > ${UP}
                     echo 'report_safe 1' >> ${UP}
                     chown $username:$username  ${UP}
                     chmod 644 ${UP}
        fi
        chown  ${username}:mail $DIR
        chmod 771 $DIR
done

# Rewrite Rspamd configs for users
echo "action=rewrite&value=rspamd" >> /usr/local/directadmin/data/task.queue
